version: "2"

services:

  image-uploader:
    image: image-uploader
    container_name: image-uploader
    build:
      context: .
    ports:
      - "8080:8080"

  # db:
  #   image: mongo
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"