version: "3.8"

services:
  app:
    image: image-uploader:latest
    container_name: image-uploader
    build:
      context: .
    ports:
      - 8081:8081
    environment:
      - PORT=8081
    volumes:
      - ./:/go/src/app