version: "2"

services:
  app:
    image: image-uploader
    container_name: image-uploader
    build:
      context: .
    ports:
      - "8081:8081"
    env_file:
    - docker-env.list
  # db:
  #   image: mongo
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"